### ISSUE TITLE
Filed to parse version 02 skn file

### ISSUE THREAD

**Issue by ArcEcho** [EldegarThundertale/lolbie#3]
[Ahri.zip](https://github.com/EldegarThundertale/lolbie/files/966523/Ahri.zip)
It is version 02  according to the 4th and 5th byte data. Blender crashes after importing this file. In debug mode the console says invalid access but no backtrace infomation.Is there any  way to show backtrace infomantion in console directly?

version:2.78c

**Comment by ArcEcho** [comment]
I think there is something wrong with the IO module in which uint16 and int16 read negtive number for vertex index(the value seems right).
Here is the offical test_box.skn, simple but failed to load.
[Test_Box.zip](https://github.com/EldegarThundertale/lolbie/files/967029/Test_Box.zip)

**Comment by EldegarThundertale** [comment]
I've understand, if you solved the problem make a pull request.

**Comment by EldegarThundertale** [comment]
Actually the old version will no longer supported

**Comment by ArcEcho** [comment]
SKN use coordinate compatible with directx, vtxVector implicitly translate the coordinate from LH to RH, therefore it multiply -1 to z component.There is a faceVector class for indices，so this is not an issue，just my misunderstanding.
